image: "archlinuxjp/archlinux"

cache:
  paths:
  - /opt/rls

before_script:
- pacman -Sy --noconfirm neovim python-{neovim,pytest} git rustup base-devel cmake
- test -d "/opt/rls" || git clone https://github.com/jonathandturner/rls /opt/rls
- rustup default nightly

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo build --manifest-path=/opt/rls/Cargo.toml
  - mkdir -p $HOME/.config/nvim/rplugin
  - ln -s /builds/autozimu/LanguageClient-neovim $HOME/.config/nvim/rplugin/python3
  - make test
