# This file is a template, and might need editing before it works on your project.
# Unofficial language image. Look for the different tagged releases at:
# https://hub.docker.com/r/scorpil/rust/tags/
image: "scorpil/rust:nightly"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends git
- git clone https://github.com/jonathandturner/rls /opt/rls

# Use cargo to test the project
test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - py.test
