[package]
name = "languageclient"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
description = "Language Server Protocol (LSP) client for vim and neovim"

[dependencies]
failure = "*"
log = "*"
env_logger = "*"
chrono = "*"
colored = "*"
structopt = "*"
structopt-derive = "*"
libc = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

jsonrpc-core = "*"
languageserver-types = "*"
url = "*"
pathdiff = "*"
diff = "*"
regex = "*"

clippy = {version = "*", optional = true}

[features]
default = []
