[package]
name = "languageclient"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
description = "Language Server Protocol (LSP) client for vim and neovim"
build = "build.rs"

[dependencies]
failure = "*"
log = "*"
log4rs = "*"
structopt = "*"
structopt-derive = "*"
libc = "*"
lazy_static = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

jsonrpc-core = "*"
languageserver-types = "*"
url = "*"
pathdiff = "*"
diff = "*"
colored = "*"
regex = "*"

[build-dependencies]
vergen = "*"
